vkbottle.auth [WIP]
vkbottle/vkbottle pull request #221
Opened 2020-10-09 16:18 UTC by dhvcc

Vkbottle authorization flows

2020-10-09 16:19 UTC, timoniq commented
нет, нет, это только в `tools`

2020-10-09 16:22 UTC, timoniq requested changes

2020-10-09 16:22 UTC, timoniq commented on vkbottle/auth/_flows.py
> +    def __init__(
Зачем переопределять инит?

2020-10-09 16:22 UTC, timoniq commented on vkbottle/auth/_flows.py
> +            display: Union[None, str] = None,
это называется Optional

2020-10-09 16:22 UTC, timoniq commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
почему оно приватное

2020-10-09 16:22 UTC, timoniq commented on vkbottle/auth/_flows.py
> +class AuthFlow:
желательно абстрактным классом

2020-10-12 13:39 UTC, dhvcc commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
Что бы скрыть функционал, который, пользователю, точно не стоит трогать
Ссылка не динамична, зачем давать лишний раз возможность её менять?

2020-10-12 14:52 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/__init__.py
> +"""
зачем называть _flows, когда можно flows? что дает эта семантика в названии?

2020-10-12 14:52 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
и опять

2020-10-12 14:52 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +    def _parse_scope(scope: Union[None, int, List[int]]) -> Union[None, int]:
и здесь

2020-10-12 14:52 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +            scope: Union[None, int, List[int]] = None,
лучше `Optional[Union[int, List[int]]]`, ставить None рядом с типами как-то неочень

2020-10-12 14:52 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +            # TODO: raise VKAuthError
для ошибок есть хорошие генераторы кстати, с которыми их удобно ловить

2020-10-12 14:53 UTC, timoniq commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
> Что бы скрыть функционал, который, пользователю, точно не стоит трогать
> Ссылка не динамична, зачем давать лишний раз возможность её менять?

а зачем ограничивать разработчика

2020-10-12 14:54 UTC, dhvcc commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +            # TODO: raise VKAuthError
Тут вообще help wanted
Мб напишешь? Я не смотрел ещё код по ошибкам, но знаю, что поменялись

2020-10-12 14:54 UTC, timoniq approved these changes

2020-10-12 14:55 UTC, dhvcc commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +    def _parse_scope(scope: Union[None, int, List[int]]) -> Union[None, int]:
Приватные методы, модули и другое
Хотя в основном коде этого не много, поэтому, наверное уберу
но oauth_link пускай останется приватом

2020-10-12 15:07 UTC, dhvcc commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +            scope: Union[None, int, List[int]] = None,
Да, но выглядит чище, нет?

2020-10-12 15:25 UTC, timoniq commented on vkbottle/tools/dev_tools/auth/_flows/user.py
> +            scope: Union[None, int, List[int]] = None,
нет, грязнее

2020-10-12 19:22 UTC, dhvcc commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
Это не ограничение, а сокрытие лишнего
Если ему реально нужно будет - всегда можно достучаться до аттрибута

2020-10-13 07:51 UTC, dhvcc commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
> > Что бы скрыть функционал, который, пользователю, точно не стоит трогать
> > Ссылка не динамична, зачем давать лишний раз возможность её менять?
> 
> а зачем ограничивать разработчика

И ещё один аргумент к сокрытию это то, что не всегда ясен интерфейс и ты натыкаешься на миллион проперти и аттрибутов
Как понять, что нужно юзать? С явным определением приватных полей разработчику будет понятно, с чем можно и нужно работать, а что лучше не трогать, пока не появится реальной необходимости
Опять же, ко всему можно достучаться

С приватными модулями, наверное, переборщил, но приватные аттрибуты и методы имеют смысл
Хотя `parse_scope` сделаю пабликом тк он может быть полезным и, так как это простой геттер, на флоу он никак не повлияет

2020-10-13 08:05 UTC, dhvcc commented on vkbottle/auth/_flows.py
> +    _OAUTH_URL = "https://oauth.vk.com/"
Кстати, одна из вещей, которые мне не нравились в боттле в2 - много импортов в инитах и много возможностей импортов одного и того же по-разному
А потом сидишь и думаешь зачем там это
Либо не делать столько импортов в инитах повсюду, либо делать приватные модули, что бы их импортировали только из, например, `from vkbottle import Class`

Тогда будет проще читать код и понимать, где нужны эти импорты и почему они именно там

2020-10-13 14:24 UTC, timoniq approved these changes

2020-10-13 14:25 UTC, merged