user implemention, and small add
vkbottle/vkbottle pull request #310
Opened 2021-02-07 09:15 UTC by Lisovq

needed to user: documentation, example, tests.
small add: use the custom rules && default custom rules

2021-02-07 10:24 UTC, timoniq requested changes

2021-02-07 10:24 UTC, timoniq commented on vkbottle/framework/bot/labeler/default.py
> +        CUSTOM_RULES.update(kwargs.get("custom_rules", {}))
не понимаю, зачем обновлять константу, а если я создам два лейблера?

2021-02-07 10:24 UTC, timoniq commented on vkbottle/dispatch/rules/user.py
> +class ABCMessageRule(ABCRule):
может все таки стоит как-то слить рулзы в одно место и с дженериками ставить тип ивента, фиксить при необходимости рул в двух местах - такое себе

2021-02-07 10:24 UTC, timoniq commented on vkbottle/bot.py
> +from .framework.bot import ABCBotLabeler, Bot, BotBlueprint, BotLabeler, bot_run_multibot
что-то раздражает глаза, наверное тавтология, возможно стоит оставить `run_multibot` для бота и `run_multi_userbot`, например, для юзербота, еще вариант - оставить все как было с одинаковыми названиями, что не так страшно ведь импортятся они из конкретных мест, и еще вариант - сделать шорткаты красивых названий в которых возможно сломается типизация так что вариант не очень

2021-02-24 09:19 UTC, MazZz3R commented
какие-нибудь изменения по этому пр будут?

2021-02-24 09:31 UTC, Ne0shka commented
> какие-нибудь изменения по этому пр будут?

Несомненно будут. Вы также можете предложить свои изменения - форк тоже opensource.

2021-03-05 09:32 UTC, Lisovq commented on vkbottle/framework/bot/labeler/default.py
> +        CUSTOM_RULES.update(kwargs.get("custom_rules", {}))
хм, может тогда делать .copy() и .update?, логичным не вижу когда ставишь свои кастом рулы - дропаются дефолтные

2021-03-08 18:33 UTC, markelovstyle commented
Когда апрув? Или есть еще вещи, которые нужно доделать? Если да, то составьте список

2021-03-08 18:51 UTC, Ne0shka commented
> Когда апрув? Или есть еще вещи, которые нужно доделать? Если да, то составьте список

- документация
- экземплы
- тесты

Это указано в описании PRа

2021-04-20 01:42 UTC, closed without merging