Add `event_data` generator
vkbottle/vkbottle pull request #389
Opened 2021-08-27 17:30 UTC by yilbegan

Добавлен генератор `event_data` для [send_message_event_answer](https://vk.com/dev/messages.sendMessageEventAnswer).
```python
from vkbottle import ShowSnackbarEvent
ShowSnackbarEvent(text="Сейчас я исчезну!").get_json()  # '{"text": "Сейчас я исчезну!", "type": "show_snackbar"}'
```

Связанные issue: #374

* [x] Ваш код документирован.
* [x] Для вашего кода есть тесты.
* [x] Для вашего кода есть примеры использования в examples.

2021-08-27 21:17 UTC, ghost requested changes
Почему бы не использовать `pydantic.BaseModel`?

2021-08-27 21:39 UTC, yilbegan commented
> Почему бы не использовать `pydantic.BaseModel`?

Изначально так и хотел, но в зависимостях его нет, ради двух строчек добавлять такое себе.

2021-08-27 21:42 UTC, yilbegan commented
> Почему бы не использовать `pydantic.BaseModel`?

Хотя его `vkbottle_types` тянет, поправлю.

2021-08-28 09:25 UTC, vanburgerberg commented
Другое дело. Только тестировать модельки не нужно)

2021-08-28 09:59 UTC, timoniq approved these changes

2021-08-28 09:59 UTC, timoniq commented
спасибо!

2021-08-28 10:00 UTC, merged

2021-08-28 10:10 UTC, timoniq commented
увидев чекпоинт с документацией, пропустил, что его на самом деле не должно было быть. открыл issue