Улучшенная система контекстных переменных
vkbottle/vkbottle pull request #601
Opened 2022-12-27 19:09 UTC by lightmanLP

Какую проблему решает ваш PR:
Система контекстых переменных для миддлварей полностью переделана. `context_variables` теперь доступны для чтения и изменения в pre/post миддлварях и правилах. Так же добавлен self reference по имени `context`.

Связанные issue: # .

* [ ] Ваш код документирован.
* [ ] Для вашего кода есть тесты.
* [ ] Для вашего кода есть примеры использования в examples.

2022-12-27 19:11 UTC, ZeN220 commented
@lightmanLP а тесты

2022-12-27 19:12 UTC, lightmanLP commented
> @lightmanLP а тесты

Я не против, если ты их напишешь)
Написал на базе апдейта систему, она работает. Юнит тесты не писал.

2022-12-27 19:14 UTC, ZeN220 commented
@lightmanLP ну раз уж сел писать функциональность, то стоит и тестами заняьься

2022-12-27 19:15 UTC, lightmanLP commented
> @lightmanLP ну раз уж сел писать функциональность, то стоит и тестами заняьься

когда-нибудь

2022-12-27 19:59 UTC, lightmanLP commented
Про проблему с типами https://github.com/python/mypy/issues/11488
Можно выбрать на вкус и цвет под кодстайл проекта

2022-12-27 20:14 UTC, FeeeeK requested changes

2022-12-27 20:14 UTC, axd1x8a commented on vkbottle/dispatch/views/abc/message.py
> +        context_variables["context"] = context_variables
Зачем хранить ссылку на словарь внутри словаря?

2022-12-27 20:14 UTC, FeeeeK commented on vkbottle/dispatch/middlewares/abc.py
> +    async def pre(self, context_variables: Optional[dict] = None) -> None:
Вместо этого можно просто сделать атрибут контекст к мидлварям и инициализировать их с ним.

2022-12-27 20:14 UTC, FeeeeK commented on vkbottle/dispatch/middlewares/abc.py
> -    def send(self, context_update: Optional[dict] = None) -> None:
Не ломайте обратную совместимость.

2022-12-27 20:14 UTC, FeeeeK commented on vkbottle/dispatch/rules/abc.py
> +        context_variables: Optional[dict] = None
Вместо этого можно повторить то, что есть в мидлварях, но вместо инициализации переопределить `__call__`, и передавать туда временный контекст, доступный по `self.context`

2022-12-27 20:17 UTC, FeeeeK commented
> Про проблему с типами [python/mypy#11488](https://github.com/python/mypy/issues/11488) Можно выбрать на вкус и цвет под кодстайл проекта

mypy ругается совсем на другое. А это ишью кажется мне неправильным, для оверлоадов всегда нужна реализация.

2022-12-28 07:51 UTC, lightmanLP commented on vkbottle/dispatch/rules/abc.py
> +        context_variables: Optional[dict] = None
А коллизия? У правила то, в отличие от мидлваря, инстанс один всегда. Стейтфул это плохо.

2022-12-28 07:52 UTC, lightmanLP commented on vkbottle/dispatch/views/abc/message.py
> +        context_variables["context"] = context_variables
Чтобы даже из хендлера их можно было модифицировать, получая в виде дикта. После хендлера доступ еще имеет post мидлварь.

2022-12-28 08:04 UTC, lightmanLP commented
> mypy ругается совсем на другое.
Сначала он ругается именно на это.
![image](https://user-images.githubusercontent.com/50497969/209779369-cd24da9a-05f5-41bb-94cb-497fd3a7a84c.png)

> А это ишью кажется мне неправильным, для оверлоадов всегда нужна реализация.
С чего бы в абстрактных классах должна быть конкретная реализация?

2023-07-12 18:14 UTC, timoniq commented
привет, спасибо за PR! 
новые мидлвари двух видов - с shared и иммутабельным контекстом запланированы к следующему major-релизу

https://botoforum.notion.site/Middlewares-Refactoring-556f5afd228a4b82bc6ad3ec8ba38140

я смержу в v4 и напишу тесты когда закончу с организацией rolling релизов

2024-09-14 15:45 UTC, closed without merging