Fix bug with redirect_uri in UserAuth
vkbottle/vkbottle pull request #700
Opened 2023-04-17 23:39 UTC by FastCodeProfile

An error occurred when trying to get a token using UserAuth only in cases of a blocked account

2023-07-12 21:29 UTC, timoniq commented
привет 👋  спасибо за PR
я вижу что была создан отдельный класс для ошибки AccountBlocked
так ли нужно это разделение? появилось много нарушений принципа DRY

2023-07-12 21:49 UTC, FastCodeProfile commented
Привет, я добавил новый класс AccountBlocked для обработки блокировок аккаунтов. Однако, я заметил, что это противоречит принципам DRY (Don't Repeat Yourself). Извините, что не изучил подход к написанию кода вашей библиотеки, у меня не было на это времени.
Я считаю, что лучшим решением будет либо устранить нарушение принципа DRY, либо поместить это исключение в ваш главный класс исключений VKAPIError. Поправьте меня, если я ошибаюсь.

2023-07-13 01:08 UTC, timoniq requested changes

2023-07-13 01:08 UTC, timoniq commented on vkbottle/tools/auth.py
> +            response["error_type"] = "blocked"
Не совсем понимаю зачем здесь устанавливается `error_type`? Он ведь так всегда одинаковый

2023-07-13 01:08 UTC, timoniq commented on vkbottle/tools/auth.py
> +        if response["error_msg"] == "need_validation":
Не думаю что это будет лучшим решением. Так можно в итоге добавлять условие на каждый тип ошибки, лучше сделать маппинг error_msg к классу ошибки

2023-07-13 01:08 UTC, timoniq commented on vkbottle/tools/auth.py
> +class AccountBlocked(VKAPIError, code=3):
Мне нужно понимание имеет ли смысл вообще выносить эту ошибку как отдельный класс. Какую проблему это решает? Разве это нельзя поймать просто как `VKAPIError[3]`?

2023-07-13 10:36 UTC, FastCodeProfile commented on vkbottle/tools/auth.py
> +class AccountBlocked(VKAPIError, code=3):
Да по идеи можно, честно сказать я уже не помню почему я пришел к такому решению.

2023-07-13 13:52 UTC, timoniq commented on vkbottle/tools/auth.py
> +class AccountBlocked(VKAPIError, code=3):
> Да по идеи можно, честно сказать я уже не помню почему я пришел к такому решению.

тогда я закрою PR, когда ты причину можешь оформить issue, и я напишу подходящую реализацию

2023-07-13 13:53 UTC, closed without merging

2023-07-13 13:55 UTC, FastCodeProfile commented
Оке

чт, 13 июл. 2023 г., 16:53 Arseny Kriuchkov ***@***.***>:

> Closed #700 <https://github.com/vkbottle/vkbottle/pull/700>.
>
> —
> Reply to this email directly, view it on GitHub
> <https://github.com/vkbottle/vkbottle/pull/700#event-9811499567>, or
> unsubscribe
> <https://github.com/notifications/unsubscribe-auth/AW3SCQTODHCDFKK52Y562JLXP74UZANCNFSM6AAAAAAXB3JRA4>
> .
> You are receiving this because you authored the thread.Message ID:
> ***@***.***>
>